### ISSUE TITLE
feature/confirmation enhancement

### ISSUE THREAD

**Issue by itspatys** [itspatys/POLmed#11]
![obraz](https://user-images.githubusercontent.com/58817270/150214037-896034f9-7aab-4191-b691-f0d5c99a5540.png)
User should also be able to cancel the appointment. 

![obraz](https://user-images.githubusercontent.com/58817270/150214311-70a4123f-d14e-4168-b755-3b7ef3188b93.png)
I also think that styling on mobile isn't that good.

**Comment by kostnerek** [comment]
should be fixed:)
